name: code
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.15.0
  jitsi_meet_wrapper: ^0.0.4
  syncfusion_localizations: ^20.1.50
  cupertino_icons: ^1.0.4
  kiwi: ^4.0.1
  rxdart: ^0.27.3
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  image_picker: ^0.8.4+4
  image_gallery_saver: ^1.7.1
  mime: ^1.0.1
  http: ^0.13.4
  dio: ^4.0.4
  file_picker: ^4.3.2
  flutter_slidable: ^1.2.0
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.18
  devicelocale: ^0.5.0
  fluttertoast: ^8.0.8
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  scrollable_positioned_list: ^0.3.2
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flutter_html: ^3.0.0-alpha.2
  flutter_parsed_text: ^2.2.1
  web_socket_channel: ^2.1.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^2.2.0
  share_plus: ^4.0.4
  open_file: ^3.2.1
  uuid: ^3.0.5
  image_cropper: ^2.0.2
  percent_indicator: ^4.0.0
  multi_image_picker2: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_emoji: ^2.4.0
  emoji_picker_flutter: ^1.0.8
  ### Firebase
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.4.5
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.14
  ###
  flutter_local_notifications: ^10.0.0-dev.13
  keyboard_actions: ^4.0.0
  media_scanner_scan_file: ^0.0.3
  video_player: ^2.2.14
  chewie: ^1.2.2
  android_external_storage: ^0.1.0
  receive_sharing_intent: ^1.4.5
  sqflite: ^2.0.2
  audioplayers: ^0.20.1
  vibration: ^1.7.4-nullsafety.0
  flutter_lints: ^2.0.1
  another_audio_recorder: ^1.0.1
  timeline_tile: ^2.0.0
  syncfusion_flutter_calendar: ^20.1.50
  syncfusion_flutter_datepicker: ^20.1.50
  flutter_speed_dial: ^6.0.0
  flash: ^2.0.3+2
  google_sign_in: ^5.2.3
  sign_in_with_apple: ^3.3.0
  heic_to_jpg: ^0.2.0
  uni_links: ^0.5.1
  intl_phone_number_input: ^0.7.0+2
  otp: ^3.0.2
  mobile_scanner: ^1.0.0
  base32: ^2.1.1
  flutter_callkit_incoming: ^1.0.2+1
  flutter_colorpicker: ^1.0.3
  youtube_player_iframe: ^2.3.0
  flutter_app_badger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - lib/_res/assets/
    - lib/_res/assets/img/
    - lib/_res/assets/img/reactions/
    - lib/_res/assets/img/activities/
    - lib/_res/assets/img/sessions/
    - lib/_res/assets/img/themes/
    - lib/_res/assets/countries.json
    - lib/_res/assets/paises.json
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: EmojiOne
      fonts:
        - asset: lib/_res/assets/fonts/EmojiOneColor.otf
    - family: SourceSansPro
      fonts:
        - asset: lib/_res/assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: lib/_res/assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: lib/_res/assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: lib/_res/assets/fonts/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: lib/_res/assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: lib/_res/assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: lib/_res/assets/fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
#    - family: Montserrat
#      fonts:
#        - asset: lib/_res/assets/fonts/montserrat_bold.ttf
#        - asset: lib/_res/assets/fonts/montserrat_medium.ttf
#        - asset: lib/_res/assets/fonts/montserrat_regular.ttf
#        - asset: lib/_res/assets/fonts/proxima_nova_bold_alt.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_light_alt.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_thin_alt.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_black.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_bold.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_extrabold.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_thin.otf
#        - asset: lib/_res/assets/fonts/proxima_nova_regular.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
